-- Add major missing AI tools across key categories
-- Focus on: Code editors, Productivity, Chat/Search, Design, Data Science

INSERT INTO public.ai_tools (name, slug, website_url, description, full_description, company_name, company_website, contact_email, primary_category_id, logo_url, pricing_model, pricing_tier, monthly_price, annual_price, has_free_trial, trial_duration_days, key_features, use_cases, platforms, ai_models_used, api_available, founded_year, is_open_source, status, is_featured, is_verified, rating, review_count, favorite_count, view_count)
SELECT * FROM (VALUES
  -- AI Code Editors
  ('Cursor', 'cursor', 'https://cursor.sh', 'AI-powered code editor built on VSCode', 'Cursor is the AI-first code editor designed for pair programming with AI. Built on VSCode with enhanced AI capabilities.', 'Anysphere', 'https://cursor.sh', 'support@cursor.sh', (SELECT id FROM public.tool_categories WHERE slug = 'code-development' LIMIT 1), 'https://cursor.sh/favicon.ico', 'freemium', 'Pro', 20.00, 240.00, true, 14, ARRAY['AI code completion', 'Chat with codebase', 'AI code generation', 'VSCode compatible', 'Multi-file editing'], ARRAY['Software development', 'Code refactoring', 'Bug fixing', 'Feature implementation', 'Learning to code'], ARRAY['desktop'], ARRAY['GPT-4', 'Claude'], true, 2023, false, 'approved', true, true, 4.8, 3200, 1800, 4500),

  ('Windsurf', 'windsurf', 'https://codeium.com/windsurf', 'AI-powered IDE by Codeium', 'Windsurf is Codeium''s next-generation AI IDE with agentic capabilities for intelligent code editing.', 'Codeium', 'https://codeium.com', 'support@codeium.com', (SELECT id FROM public.tool_categories WHERE slug = 'code-development' LIMIT 1), 'https://codeium.com/favicon.ico', 'freemium', 'Pro', 10.00, 120.00, true, 30, ARRAY['AI code completion', 'Agentic editing', 'Multi-language support', 'Context-aware suggestions', 'Integrated terminal'], ARRAY['Full-stack development', 'Code refactoring', 'Debugging', 'Code review', 'Prototyping'], ARRAY['desktop'], ARRAY['Proprietary AI'], true, 2024, false, 'approved', true, true, 4.6, 890, 450, 1200),

  ('Codeium', 'codeium', 'https://codeium.com', 'Free AI code completion', 'Codeium offers free AI-powered code completion for 70+ programming languages with IDE integration.', 'Codeium', 'https://codeium.com', 'support@codeium.com', (SELECT id FROM public.tool_categories WHERE slug = 'code-development' LIMIT 1), 'https://codeium.com/favicon.ico', 'free', 'Free', 0.00, 0.00, false, 0, ARRAY['Code completion', '70+ languages', 'IDE integration', 'Context awareness', 'Fast suggestions'], ARRAY['Software development', 'Learning programming', 'Productivity boost', 'Code writing', 'Multi-language projects'], ARRAY['vscode', 'jetbrains', 'web'], ARRAY['Proprietary AI'], true, 2022, false, 'approved', true, true, 4.7, 5600, 3200, 6800),

  ('Replit AI', 'replit-ai', 'https://replit.com', 'Collaborative browser IDE with AI', 'Replit is a collaborative browser-based IDE with integrated AI assistance for building and deploying applications.', 'Replit', 'https://replit.com', 'support@replit.com', (SELECT id FROM public.tool_categories WHERE slug = 'code-development' LIMIT 1), 'https://replit.com/favicon.ico', 'freemium', 'Pro', 20.00, 240.00, true, 7, ARRAY['Browser-based IDE', 'AI code generation', 'Instant deployment', 'Collaborative coding', 'Database included'], ARRAY['Learning to code', 'Rapid prototyping', 'Web development', 'API development', 'Education'], ARRAY['web'], ARRAY['GPT-4'], true, 2016, false, 'approved', true, true, 4.5, 12400, 6800, 14500),

  -- AI Chat & Search
  ('Perplexity', 'perplexity', 'https://perplexity.ai', 'AI-powered search engine', 'Perplexity AI is an answer engine that uses AI to provide accurate answers with cited sources.', 'Perplexity AI', 'https://perplexity.ai', 'support@perplexity.ai', (SELECT id FROM public.tool_categories WHERE slug = 'research-analytics' LIMIT 1), 'https://perplexity.ai/favicon.ico', 'freemium', 'Pro', 20.00, 240.00, true, 7, ARRAY['AI search', 'Source citations', 'Follow-up questions', 'Pro search mode', 'Mobile app'], ARRAY['Research', 'Fact-checking', 'Learning', 'News discovery', 'Academic work'], ARRAY['web', 'ios', 'android'], ARRAY['GPT-4', 'Claude'], true, 2022, false, 'approved', true, true, 4.7, 8900, 5400, 11200),

  ('Claude', 'claude-ai', 'https://claude.ai', 'Anthropic''s AI assistant', 'Claude is Anthropic''s advanced AI assistant with extended context and strong reasoning capabilities.', 'Anthropic', 'https://anthropic.com', 'support@anthropic.com', (SELECT id FROM public.tool_categories WHERE slug = 'productivity-automation' LIMIT 1), 'https://claude.ai/favicon.ico', 'freemium', 'Pro', 20.00, 240.00, true, 0, ARRAY['200K context window', 'Code generation', 'Document analysis', 'Creative writing', 'Artifact creation'], ARRAY['Research', 'Writing', 'Coding', 'Analysis', 'Brainstorming'], ARRAY['web', 'api'], ARRAY['Claude 3.5 Sonnet'], true, 2023, false, 'approved', true, true, 4.8, 15600, 9200, 18900),

  -- Productivity Tools
  ('Notion AI', 'notion-ai', 'https://notion.so', 'AI-powered workspace', 'Notion AI brings artificial intelligence to your all-in-one workspace for docs, wikis, and project management.', 'Notion', 'https://notion.so', 'support@notion.so', (SELECT id FROM public.tool_categories WHERE slug = 'productivity-automation' LIMIT 1), 'https://notion.so/favicon.ico', 'freemium', 'Plus', 10.00, 120.00, true, 0, ARRAY['AI writing', 'Document generation', 'Data autofill', 'Translation', 'Summarization'], ARRAY['Note-taking', 'Project management', 'Documentation', 'Knowledge base', 'Team collaboration'], ARRAY['web', 'desktop', 'ios', 'android'], ARRAY['GPT-4'], true, 2016, false, 'approved', true, true, 4.7, 28400, 16500, 32100),

  ('Gamma', 'gamma-ai', 'https://gamma.app', 'AI presentation maker', 'Gamma creates beautiful presentations, documents, and websites with AI in seconds.', 'Gamma', 'https://gamma.app', 'support@gamma.app', (SELECT id FROM public.tool_categories WHERE slug = 'productivity-automation' LIMIT 1), 'https://gamma.app/favicon.ico', 'freemium', 'Plus', 8.00, 96.00, true, 0, ARRAY['AI presentations', 'Smart templates', 'Interactive content', 'Analytics', 'Export options'], ARRAY['Presentations', 'Pitch decks', 'Reports', 'Documentation', 'Portfolios'], ARRAY['web'], ARRAY['GPT-4'], false, 2020, false, 'approved', true, true, 4.6, 6700, 3900, 7800),

  -- Design Tools
  ('Figma AI', 'figma-ai', 'https://figma.com', 'Collaborative design with AI', 'Figma is a collaborative design platform with AI features for UI/UX design and prototyping.', 'Figma', 'https://figma.com', 'support@figma.com', (SELECT id FROM public.tool_categories WHERE slug = 'design-creativity' LIMIT 1), 'https://figma.com/favicon.ico', 'freemium', 'Professional', 15.00, 180.00, true, 30, ARRAY['AI image generation', 'Auto layout', 'Component creation', 'Real-time collaboration', 'Prototyping'], ARRAY['UI/UX design', 'Wireframing', 'Prototyping', 'Design systems', 'Team collaboration'], ARRAY['web', 'desktop'], ARRAY['Custom AI'], true, 2016, false, 'approved', true, true, 4.8, 45600, 28900, 52300),

  ('Uizard', 'uizard', 'https://uizard.io', 'AI-powered UI design', 'Uizard transforms sketches and ideas into professional UI designs using AI.', 'Uizard', 'https://uizard.io', 'support@uizard.io', (SELECT id FROM public.tool_categories WHERE slug = 'design-creativity' LIMIT 1), 'https://uizard.io/favicon.ico', 'freemium', 'Pro', 12.00, 144.00, true, 14, ARRAY['Sketch to design', 'AI mockups', 'Component library', 'Collaboration', 'Export code'], ARRAY['Rapid prototyping', 'Wireframing', 'App design', 'Landing pages', 'MVP design'], ARRAY['web'], ARRAY['Computer vision AI'], false, 2018, false, 'approved', true, true, 4.5, 3200, 1800, 3900),

  -- Data Science & Analytics
  ('Julius AI', 'julius-ai', 'https://julius.ai', 'AI data analyst', 'Julius AI helps you analyze data, create visualizations, and extract insights using natural language.', 'Julius AI', 'https://julius.ai', 'support@julius.ai', (SELECT id FROM public.tool_categories WHERE slug = 'research-analytics' LIMIT 1), 'https://julius.ai/favicon.ico', 'freemium', 'Pro', 20.00, 240.00, true, 7, ARRAY['Data analysis', 'Visualization', 'Statistical modeling', 'Natural language queries', 'Report generation'], ARRAY['Data analysis', 'Business intelligence', 'Research', 'Financial analysis', 'Report creation'], ARRAY['web'], ARRAY['GPT-4'], true, 2023, false, 'approved', true, true, 4.6, 2100, 1200, 2800),

  ('DataCamp AI', 'datacamp-ai', 'https://datacamp.com', 'Learn data science with AI', 'DataCamp offers interactive data science courses with AI-powered personalized learning paths.', 'DataCamp', 'https://datacamp.com', 'support@datacamp.com', (SELECT id FROM public.tool_categories WHERE slug = 'education-learning' LIMIT 1), 'https://datacamp.com/favicon.ico', 'freemium', 'Premium', 25.00, 300.00, true, 7, ARRAY['Interactive courses', 'AI tutor', 'Hands-on practice', 'Skill assessments', 'Certificates'], ARRAY['Learning Python', 'Data analysis', 'Machine learning', 'SQL training', 'Career development'], ARRAY['web'], ARRAY['Custom AI'], false, 2013, false, 'approved', true, true, 4.6, 18900, 11200, 21400),

  -- Marketing & Content
  ('Jasper', 'jasper-ai', 'https://jasper.ai', 'AI content creation platform', 'Jasper is an AI copilot for marketing teams to create on-brand content faster.', 'Jasper AI', 'https://jasper.ai', 'support@jasper.ai', (SELECT id FROM public.tool_categories WHERE slug = 'marketing-sales' LIMIT 1), 'https://jasper.ai/favicon.ico', 'paid', 'Creator', 49.00, 588.00, true, 7, ARRAY['Content generation', 'Brand voice', 'SEO optimization', 'Team collaboration', 'Image generation'], ARRAY['Blog writing', 'Marketing copy', 'Social media', 'Email campaigns', 'Ad copy'], ARRAY['web', 'chrome'], ARRAY['GPT-4'], true, 2021, false, 'approved', true, true, 4.5, 12300, 6900, 14200),

  ('HubSpot AI', 'hubspot-ai', 'https://hubspot.com', 'AI-powered CRM', 'HubSpot combines CRM with AI tools for marketing, sales, and customer service automation.', 'HubSpot', 'https://hubspot.com', 'support@hubspot.com', (SELECT id FROM public.tool_categories WHERE slug = 'business-operations' LIMIT 1), 'https://hubspot.com/favicon.ico', 'freemium', 'Professional', 890.00, 10680.00, true, 14, ARRAY['AI content assistant', 'Lead scoring', 'Email automation', 'Analytics', 'Workflow automation'], ARRAY['CRM', 'Marketing automation', 'Sales pipeline', 'Customer service', 'Analytics'], ARRAY['web', 'mobile'], ARRAY['GPT-4'], true, 2006, false, 'approved', true, true, 4.4, 34500, 19800, 42100)
) AS new_tools (name, slug, website_url, description, full_description, company_name, company_website, contact_email, primary_category_id, logo_url, pricing_model, pricing_tier, monthly_price, annual_price, has_free_trial, trial_duration_days, key_features, use_cases, platforms, ai_models_used, api_available, founded_year, is_open_source, status, is_featured, is_verified, rating, review_count, favorite_count, view_count)
WHERE NOT EXISTS (
  SELECT 1 FROM public.ai_tools WHERE slug = new_tools.slug
);
