-- Add 20 unique AI tools across diverse categories
-- Focus on: Image generation, Video, Audio, Writing, Business, Education, Healthcare

INSERT INTO public.ai_tools (name, slug, website_url, description, full_description, company_name, company_website, contact_email, primary_category_id, logo_url, banner_image_url, video_url, pricing_model, pricing_tier, monthly_price, annual_price, has_free_trial, trial_duration_days, key_features, use_cases, platforms, ai_models_used, api_available, founded_year, is_open_source, status, is_featured, is_verified, rating, review_count, favorite_count, view_count)
SELECT * FROM (VALUES
  -- Image Generation & Visual Tools
  ('Leonardo AI', 'leonardo-ai', 'https://leonardo.ai', 'AI art generation for game assets', 'Leonardo AI creates stunning game assets, concept art, and visual content with advanced AI models and fine-tuned controls.', 'Leonardo Interactive', 'https://leonardo.ai', 'support@leonardo.ai', (SELECT id FROM public.tool_categories WHERE slug = 'image-visual' LIMIT 1), 'https://leonardo.ai/favicon.ico', 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example1', 'freemium', 'Artisan', 12.00, 144.00, true, 7, ARRAY['AI image generation', 'Game asset creation', 'Fine-tuned models', 'Prompt generation', 'Image editing'], ARRAY['Game development', 'Concept art', 'Marketing materials', 'Character design', 'Environment art'], ARRAY['web'], ARRAY['Stable Diffusion', 'Custom models'], true, 2022, false, 'approved', true, true, 4.7, 8900, 5200, 12400),

  ('Ideogram', 'ideogram', 'https://ideogram.ai', 'AI text-to-image with perfect text rendering', 'Ideogram excels at generating images with accurate text rendering, logos, and typography-heavy designs.', 'Ideogram', 'https://ideogram.ai', 'support@ideogram.ai', (SELECT id FROM public.tool_categories WHERE slug = 'image-visual' LIMIT 1), 'https://ideogram.ai/favicon.ico', 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example2', 'freemium', 'Plus', 8.00, 96.00, true, 0, ARRAY['Text rendering', 'Logo generation', 'Style control', 'High resolution', 'Commercial license'], ARRAY['Logo design', 'Poster creation', 'Social media graphics', 'Typography art', 'Branding'], ARRAY['web'], ARRAY['Proprietary AI'], true, 2023, false, 'approved', true, true, 4.6, 4200, 2800, 6100),

  ('Stability AI', 'stability-ai', 'https://stability.ai', 'Open-source generative AI models', 'Stability AI develops open-source generative AI models including Stable Diffusion for images and Stable Audio.', 'Stability AI', 'https://stability.ai', 'info@stability.ai', (SELECT id FROM public.tool_categories WHERE slug = 'image-visual' LIMIT 1), 'https://stability.ai/favicon.ico', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example3', 'freemium', 'Pro', 20.00, 240.00, true, 0, ARRAY['Stable Diffusion', 'Open source', 'API access', 'Multiple models', 'Commercial use'], ARRAY['Image generation', 'Research', 'Creative projects', 'Product visualization', 'Art creation'], ARRAY['web', 'api'], ARRAY['Stable Diffusion XL', 'Stable Audio'], true, 2020, true, 'approved', true, true, 4.7, 12600, 8100, 15900),

  -- Video & Animation
  ('Pika', 'pika-labs', 'https://pika.art', 'AI video generation from text and images', 'Pika turns text prompts and images into engaging video content with powerful editing capabilities.', 'Pika Labs', 'https://pika.art', 'support@pika.art', (SELECT id FROM public.tool_categories WHERE slug = 'video-animation' LIMIT 1), 'https://pika.art/favicon.ico', 'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example4', 'freemium', 'Pro', 10.00, 120.00, true, 0, ARRAY['Text to video', 'Image to video', 'Video editing', 'Style transfer', 'Extend videos'], ARRAY['Marketing videos', 'Social media content', 'Animated stories', 'Product demos', 'Creative projects'], ARRAY['web'], ARRAY['Proprietary AI'], false, 2023, false, 'approved', true, true, 4.5, 3400, 2100, 5200),

  ('HeyGen', 'heygen', 'https://heygen.com', 'AI video avatars and translation', 'HeyGen creates professional videos with AI avatars, voice cloning, and automatic translation into 40+ languages.', 'HeyGen', 'https://heygen.com', 'support@heygen.com', (SELECT id FROM public.tool_categories WHERE slug = 'video-animation' LIMIT 1), 'https://heygen.com/favicon.ico', 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example5', 'freemium', 'Creator', 29.00, 348.00, true, 14, ARRAY['AI avatars', 'Voice cloning', '40+ languages', 'Video translation', 'Custom avatars'], ARRAY['Training videos', 'Marketing content', 'Presentations', 'E-learning', 'Social media'], ARRAY['web'], ARRAY['GPT-4', 'Voice AI'], true, 2020, false, 'approved', true, true, 4.6, 6700, 4100, 8900),

  ('Synthesia', 'synthesia', 'https://synthesia.io', 'AI video creation with avatars', 'Synthesia enables you to create professional videos with AI avatars in minutes, no filming equipment required.', 'Synthesia', 'https://synthesia.io', 'support@synthesia.io', (SELECT id FROM public.tool_categories WHERE slug = 'video-animation' LIMIT 1), 'https://synthesia.io/favicon.ico', 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example6', 'paid', 'Starter', 29.00, 348.00, true, 14, ARRAY['120+ AI avatars', '120+ languages', 'Custom avatars', 'Screen recorder', 'Video templates'], ARRAY['Corporate training', 'Sales enablement', 'Marketing videos', 'How-to guides', 'Internal comms'], ARRAY['web'], ARRAY['Text-to-speech AI'], true, 2017, false, 'approved', true, true, 4.5, 8900, 5400, 11200),

  -- Audio & Music
  ('ElevenLabs', 'elevenlabs', 'https://elevenlabs.io', 'AI voice generation and cloning', 'ElevenLabs creates the most realistic AI voices with emotion and natural intonation for content creators.', 'ElevenLabs', 'https://elevenlabs.io', 'support@elevenlabs.io', (SELECT id FROM public.tool_categories WHERE slug = 'audio-music' LIMIT 1), 'https://elevenlabs.io/favicon.ico', 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example7', 'freemium', 'Starter', 5.00, 60.00, true, 0, ARRAY['Voice cloning', 'Multilingual', 'Emotion control', 'Voice library', 'API access'], ARRAY['Audiobooks', 'Podcasts', 'Video narration', 'Gaming', 'Accessibility'], ARRAY['web', 'api'], ARRAY['Proprietary AI'], true, 2022, false, 'approved', true, true, 4.8, 14200, 9800, 18600),

  ('Murf AI', 'murf-ai', 'https://murf.ai', 'AI voice generator for professionals', 'Murf AI offers studio-quality voiceovers with 120+ voices in 20+ languages for professional content.', 'Murf AI', 'https://murf.ai', 'support@murf.ai', (SELECT id FROM public.tool_categories WHERE slug = 'audio-music' LIMIT 1), 'https://murf.ai/favicon.ico', 'https://images.unsplash.com/photo-1589903308904-1010c2294adc?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example8', 'freemium', 'Basic', 19.00, 228.00, true, 10, ARRAY['120+ voices', '20+ languages', 'Voice changer', 'Video sync', 'Custom pronunciation'], ARRAY['E-learning', 'YouTube videos', 'Audiobooks', 'Advertisements', 'IVR systems'], ARRAY['web'], ARRAY['Text-to-speech AI'], true, 2020, false, 'approved', true, true, 4.5, 5600, 3400, 7200),

  -- Content & Writing
  ('Copy.ai', 'copy-ai', 'https://copy.ai', 'AI content writer for marketing', 'Copy.ai helps marketing teams create high-converting copy for ads, emails, blogs, and social media.', 'Copy.ai', 'https://copy.ai', 'support@copy.ai', (SELECT id FROM public.tool_categories WHERE slug = 'content-writing' LIMIT 1), 'https://copy.ai/favicon.ico', 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example9', 'freemium', 'Pro', 49.00, 588.00, true, 7, ARRAY['Marketing copy', 'Blog writer', 'Social media posts', 'Email campaigns', '90+ templates'], ARRAY['Digital marketing', 'Content creation', 'Ad copywriting', 'Blog writing', 'Social media'], ARRAY['web', 'chrome'], ARRAY['GPT-4'], true, 2020, false, 'approved', true, true, 4.4, 9800, 5900, 12100),

  ('Writesonic', 'writesonic', 'https://writesonic.com', 'AI writing and SEO optimization', 'Writesonic is an AI writing platform with SEO tools, article writer, and ChatGPT-like chat for content creation.', 'Writesonic', 'https://writesonic.com', 'support@writesonic.com', (SELECT id FROM public.tool_categories WHERE slug = 'content-writing' LIMIT 1), 'https://writesonic.com/favicon.ico', 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example10', 'freemium', 'Unlimited', 20.00, 240.00, true, 0, ARRAY['Article writer', 'SEO optimizer', 'Chatsonic AI', 'Fact-checked', '100+ templates'], ARRAY['Blog writing', 'SEO content', 'Marketing copy', 'Social posts', 'Product descriptions'], ARRAY['web', 'chrome'], ARRAY['GPT-4'], true, 2021, false, 'approved', true, true, 4.5, 11200, 6700, 13900),

  ('Grammarly', 'grammarly', 'https://grammarly.com', 'AI writing assistant', 'Grammarly uses AI to help you write clearly and mistake-free with grammar, spelling, and style suggestions.', 'Grammarly', 'https://grammarly.com', 'support@grammarly.com', (SELECT id FROM public.tool_categories WHERE slug = 'content-writing' LIMIT 1), 'https://grammarly.com/favicon.ico', 'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example11', 'freemium', 'Premium', 12.00, 144.00, true, 7, ARRAY['Grammar check', 'Style suggestions', 'Tone detector', 'Plagiarism check', 'Browser extension'], ARRAY['Professional writing', 'Academic writing', 'Email composition', 'Content editing', 'Business communication'], ARRAY['web', 'desktop', 'chrome', 'mobile'], ARRAY['Proprietary AI'], true, 2009, false, 'approved', true, true, 4.6, 32400, 21800, 45600),

  -- Business & Operations
  ('Otter.ai', 'otter-ai', 'https://otter.ai', 'AI meeting notes and transcription', 'Otter.ai automatically records and transcribes meetings with AI-generated summaries and action items.', 'Otter.ai', 'https://otter.ai', 'support@otter.ai', (SELECT id FROM public.tool_categories WHERE slug = 'business-operations' LIMIT 1), 'https://otter.ai/favicon.ico', 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example12', 'freemium', 'Pro', 10.00, 120.00, true, 0, ARRAY['Meeting transcription', 'AI summaries', 'Action items', 'Speaker ID', 'Live captions'], ARRAY['Meeting notes', 'Interviews', 'Lectures', 'Team collaboration', 'Documentation'], ARRAY['web', 'ios', 'android'], ARRAY['Speech recognition AI'], true, 2016, false, 'approved', true, true, 4.5, 18900, 12400, 23100),

  ('Zapier', 'zapier', 'https://zapier.com', 'Workflow automation platform', 'Zapier connects 5,000+ apps to automate workflows without code, now enhanced with AI capabilities.', 'Zapier', 'https://zapier.com', 'support@zapier.com', (SELECT id FROM public.tool_categories WHERE slug = 'business-operations' LIMIT 1), 'https://zapier.com/favicon.ico', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example13', 'freemium', 'Professional', 19.99, 239.88, true, 14, ARRAY['5000+ integrations', 'AI automation', 'Multi-step zaps', 'Conditional logic', 'Webhooks'], ARRAY['Business automation', 'Data sync', 'Lead management', 'Marketing automation', 'Productivity'], ARRAY['web'], ARRAY['GPT-4'], true, 2011, false, 'approved', true, true, 4.5, 45600, 28900, 56200),

  -- Education & Learning
  ('Khan Academy Khanmigo', 'khanmigo', 'https://khanacademy.org/khanmigo', 'AI tutor for students', 'Khanmigo is Khan Academy''s AI-powered tutor that provides personalized learning support for students.', 'Khan Academy', 'https://khanacademy.org', 'support@khanacademy.org', (SELECT id FROM public.tool_categories WHERE slug = 'education-learning' LIMIT 1), 'https://khanacademy.org/favicon.ico', 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example14', 'freemium', 'Premium', 9.00, 108.00, true, 0, ARRAY['AI tutoring', 'Personalized learning', 'Homework help', 'Writing feedback', 'Math support'], ARRAY['K-12 education', 'Homework help', 'Test prep', 'Math learning', 'Essay writing'], ARRAY['web'], ARRAY['GPT-4'], false, 2023, false, 'approved', true, true, 4.7, 8900, 6200, 11400),

  ('Duolingo Max', 'duolingo-max', 'https://duolingo.com', 'AI-powered language learning', 'Duolingo Max uses GPT-4 to provide personalized language lessons with AI conversation practice.', 'Duolingo', 'https://duolingo.com', 'support@duolingo.com', (SELECT id FROM public.tool_categories WHERE slug = 'education-learning' LIMIT 1), 'https://duolingo.com/favicon.ico', 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example15', 'freemium', 'Max', 29.99, 167.88, true, 14, ARRAY['40+ languages', 'AI conversations', 'Explain mistakes', 'Roleplay scenarios', 'Personalized review'], ARRAY['Language learning', 'Travel prep', 'Career development', 'Cultural education', 'Communication skills'], ARRAY['web', 'ios', 'android'], ARRAY['GPT-4'], false, 2011, false, 'approved', true, true, 4.6, 67800, 45200, 89400),

  -- Healthcare & Science
  ('Consensus', 'consensus', 'https://consensus.app', 'AI research paper search', 'Consensus uses AI to search and summarize scientific research papers, extracting insights from peer-reviewed studies.', 'Consensus', 'https://consensus.app', 'support@consensus.app', (SELECT id FROM public.tool_categories WHERE slug = 'healthcare-science' LIMIT 1), 'https://consensus.app/favicon.ico', 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example16', 'freemium', 'Premium', 8.99, 107.88, true, 7, ARRAY['Paper search', 'AI summaries', 'Citation extraction', 'Study analysis', 'Evidence synthesis'], ARRAY['Academic research', 'Literature review', 'Evidence-based decisions', 'Scientific writing', 'Medical research'], ARRAY['web'], ARRAY['GPT-4', 'Custom NLP'], true, 2021, false, 'approved', true, true, 4.6, 5400, 3800, 6900),

  ('Elicit', 'elicit', 'https://elicit.com', 'AI research assistant', 'Elicit automates research workflows like summarizing papers, extracting data, and synthesizing findings.', 'Elicit', 'https://elicit.com', 'support@elicit.com', (SELECT id FROM public.tool_categories WHERE slug = 'research-analytics' LIMIT 1), 'https://elicit.com/favicon.ico', 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example17', 'freemium', 'Plus', 10.00, 120.00, true, 0, ARRAY['Literature review', 'Data extraction', 'Paper summaries', 'Research synthesis', 'Citation finding'], ARRAY['Academic research', 'Systematic reviews', 'Meta-analysis', 'Grant writing', 'Thesis research'], ARRAY['web'], ARRAY['GPT-4'], true, 2021, false, 'approved', true, true, 4.7, 4200, 2900, 5600),

  -- Marketing & Sales
  ('Descript', 'descript', 'https://descript.com', 'AI video and podcast editor', 'Descript edits audio and video by editing text transcripts, with AI voices and screen recording.', 'Descript', 'https://descript.com', 'support@descript.com', (SELECT id FROM public.tool_categories WHERE slug = 'video-animation' LIMIT 1), 'https://descript.com/favicon.ico', 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example18', 'freemium', 'Creator', 12.00, 144.00, true, 0, ARRAY['Text-based editing', 'AI voices', 'Screen recording', 'Transcription', 'Studio sound'], ARRAY['Podcast editing', 'Video production', 'Screen recording', 'Content creation', 'Remote interviews'], ARRAY['desktop'], ARRAY['Speech AI'], true, 2017, false, 'approved', true, true, 4.6, 11200, 7800, 14300),

  ('Salesforce Einstein', 'salesforce-einstein', 'https://salesforce.com/einstein', 'AI-powered CRM intelligence', 'Einstein brings AI to Salesforce CRM with predictive analytics, automated workflows, and intelligent insights.', 'Salesforce', 'https://salesforce.com', 'support@salesforce.com', (SELECT id FROM public.tool_categories WHERE slug = 'business-operations' LIMIT 1), 'https://salesforce.com/favicon.ico', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example19', 'paid', 'Enterprise', 165.00, 1980.00, true, 30, ARRAY['Predictive analytics', 'Lead scoring', 'Automated insights', 'Natural language queries', 'Workflow automation'], ARRAY['Sales forecasting', 'Customer insights', 'Marketing automation', 'Service optimization', 'Analytics'], ARRAY['web', 'mobile'], ARRAY['Proprietary AI', 'GPT'], true, 1999, false, 'approved', true, true, 4.3, 78900, 42100, 98600),

  ('Canva AI', 'canva-ai', 'https://canva.com', 'AI-powered design platform', 'Canva uses AI to help anyone create professional designs with Magic Design, background removal, and text-to-image.', 'Canva', 'https://canva.com', 'support@canva.com', (SELECT id FROM public.tool_categories WHERE slug = 'design-creativity' LIMIT 1), 'https://canva.com/favicon.ico', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&h=400&fit=crop', 'https://www.youtube.com/watch?v=example20', 'freemium', 'Pro', 12.99, 119.99, true, 30, ARRAY['Magic Design', 'AI image generation', 'Background remover', 'Brand kit', '250K+ templates'], ARRAY['Social media graphics', 'Presentations', 'Marketing materials', 'Branding', 'Print designs'], ARRAY['web', 'ios', 'android', 'desktop'], ARRAY['Stable Diffusion', 'Custom AI'], true, 2013, false, 'approved', true, true, 4.7, 123400, 89200, 156700)
) AS new_tools (name, slug, website_url, description, full_description, company_name, company_website, contact_email, primary_category_id, logo_url, banner_image_url, video_url, pricing_model, pricing_tier, monthly_price, annual_price, has_free_trial, trial_duration_days, key_features, use_cases, platforms, ai_models_used, api_available, founded_year, is_open_source, status, is_featured, is_verified, rating, review_count, favorite_count, view_count)
WHERE NOT EXISTS (
  SELECT 1 FROM public.ai_tools WHERE slug = new_tools.slug
);
